### ISSUE TITLE
Build with Xdmf support

### ISSUE THREAD

**Issue by AntoineD** [AnacondaRecipes/vtk-feedstock#1]
Hello,

would it be possible to build vtk with xdmf support?

Cheers,
Antoine.

**Comment by nehaljwani** [comment]
Could you send a PR? The recipe assumes you build it on this container:  https://github.com/conda/conda-concourse-ci/blob/master/docker/c3i-linux-64/Dockerfile

**Comment by AntoineD** [comment]
Hi @nehaljwani,
I just created a PR, unfortunately I cannot use docker, but I was able to build and test locally.
Cheers.

**Comment by nehaljwani** [comment]
Thanks, I will take a look later today or sometime tomorrow.

**Comment by nehaljwani** [comment]
Do you also have a way to verify it?

**Comment by AntoineD** [comment]
I built the recipe with no rendering backend (it's not commited in the PR) because the build fails otherwise on my machine, also the tests from meta.yaml fail when ran by the conda build but they are OK (but the rendering dependent ones on my machine) when done by hand.

**Comment by AntoineD** [comment]
Hello @nehaljwani ,
please kindly let me know if you need more information to update the package.

**Comment by nehaljwani** [comment]
8.2.0 has been built with Xdmf support.

**Comment by AntoineD** [comment]
@nehaljwani  Thanks a lot!
